# Generated by Django 3.2.12 on 2023-01-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domains', models.CharField(max_length=100)),
                ('emails', models.CharField(max_length=100)),
                ('passwords', models.CharField(max_length=100)),
                ('hints', models.CharField(max_length=100)),
                ('mobile_numbers', models.CharField(max_length=10)),
            ],
        ),
    ]
